sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
before_script:
  - composer self-update
  - composer install
script:
  - chmod -R 777 tests/build
  - phpunit
after_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then php vendor/bin/coveralls -v; fi
